version: 2.1
orbs:
  slack: circleci/slack@4.4.3

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: mvn package

  deploy:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: mvn deploy
      - store_artifacts:
          path: target/mvn-repo
      - run:
          command: |
            cp -r target/mvn-repo/ mvn-repo/
            cd mvn-repo/
            git fetch https://github.com/taraskovaliv/treeko.repository.git master
            git config user.email "taras19041@gmail.com"
            git config user.name "taras"
            git add . -f
            git commit -m "Update via CircleCI"
            git push -f -q https://${GITHUB_TOKEN}@github.com/taraskovaliv/treeko.repository.git master
#     Notifications
      - slack/notify:
          channel: deploys
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: deploys
          event: pass
          template: basic_success_1

workflows:
  build-test-deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build
