version: 2.1
orbs:
  slack: circleci/slack@4.4.3

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: mvn package

  deploy:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: mvn deploy
      - run:
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "taras19041@gmail.com"
            git config user.name "taras"
            git add .
            git commit -m "Update via CircleCI"
            git push -q https://${GITHUB_USERNAME}:{GITHUB_PASSWORD}@github.com/taraskovaliv/treeko.repository.git master
#     Notifications
      - slack/notify:
          channel: builds
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: builds
          event: pass
          template: basic_success_1

workflows:
  build-test-deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build
